### ISSUE TITLE
Problem with the thumb generation only on FTP

### ISSUE THREAD

**Issue by davidprati** [area17/subfolio#4]
Hello,

First thanks for this amazing product.
I try Subfolio on my computer, using MAMP Pro, everything work fine.

When I try using subfolio on my ftp server, the thumbnails (and the full-size image) are not displayed.
Here:
![capture d ecran 2016-06-21 a 13 12 55](https://cloud.githubusercontent.com/assets/4788388/16227870/aea72d9a-37b3-11e6-8927-a8880dd20afc.png)

But if I disconnect/reconnect on my FTP, I see that the thumbnail exists:
![capture d ecran 2016-06-21 a 13 24 58](https://cloud.githubusercontent.com/assets/4788388/16227890/c6336032-37b3-11e6-89a9-a42b13d8c480.png)

All my folders/files are 777. My hosting solution is OVH Pro.

Thanks a lot!

**Comment by nedbaldessin** [comment]
After investigation, it turns out the issue was with the execution environment of PHP.

By default, OVH shared hosting offers execute PHP via PHP-FPM.

To revert to the legacy Apache SAPI, you must set your `.ovhconfig` to:
```
app.engine=phpcgi
```

And it'll work.

Cheers.

**Comment by entropik** [comment]
hello/bonsoir Ned

I try to install Subfolio for a personal photographique site, because I LIKE the idea of "simplicity" with a folder theme presentation...

exact same trouble with asset path than @davidprati , my upload is ok but the path of file is "File not found. "

the mode rewrite is enable, I'm on a SimpleHosting Gandi.net
https://wiki.gandi.net/fr/simple/php

![mod rewrite](https://cloud.githubusercontent.com/assets/1025402/17841034/591e188e-6814-11e6-87b2-cc7130fc0305.jpg)

thank's so much for any help...
